
["General Settings"]
	init_val_starting_level = 1.0

["Attribute 1"]
	display_name = "Durabilidad : "
	cmd_to_exc = ["/attribute @p generic.max_health base set [param(2.0)]", "/attribute @p generic.armor_toughness base set [param(0.2)] param=1.0"]
	on_level_event = ["/effect give @p minecraft:instant_health 2 3"]
	tip_to_display = "§7Aumenta tu vida y defensa."
	init_val_attribute_one = 20.0
	max_level = +inf
	base_value_per_point = 1.0
	lock = false

["Attribute 2"]
	display_name = "Fuerza : "
	cmd_to_exc = ["/attribute @p generic.attack_damage base set [param(1.1)]", "/attribute @p generic.armor base set [param(1.3)]"]
	on_level_event = ["/attribute @p minecraft:generic.max_health modifier add 0-0-0-0-2 multiply 0.2"]
	tip_to_display = "§7Endurece tu cuerpo y Aumenta tu daño cuerpo a cuerpo. "
	init_val_attribute_two = 2.0
	max_level = +inf
	base_value_per_point = 1.0
	lock = false

["Attribute 3"]
	display_name = "Frenesí : "
	cmd_to_exc = ["/attribute @p generic.attack_speed base set"]
	on_level_event = [" "]
	tip_to_display = "§7Determina que tan rapido puedes golpear con armas cuerpo a cuerpo. "
	init_val_attribute_three = 4.0
	max_level = 20.0
	base_value_per_point = 1.0
	lock = false

["Attribute 4"]
	display_name = "Destreza : "
	cmd_to_exc = ["/attribute @p attributeslib:draw_speed base set [param(0.2)]", "/attribute @p attributeslib:arrow_velocity base set [param(0.1)]", "/attribute @p attributeslib:dodge_chance base set [param(0.0125)]"]
	on_level_event = [" /attribute @p parcool:max_stamina modifier add 0-0-0-0-4 parkour 0.3 multiply", "/attribute @p attributeslib:crit_chance modifier add 0-0-0-0-9 multiply 2.0"]
	tip_to_display = "§7Disminuye el tiempo de carga del arco. Ranged goes brrrrrrrrrrrrrrr"
	init_val_attribute_forth = 4.0
	max_level = 20.0
	base_value_per_point = 1.0
	lock = false

["Attribute 5"]
	display_name = "Agilidad : "
	cmd_to_exc = ["/attribute @p generic.movement_speed base set [param(0.005)]", "/attribute @p parcool:max_stamina base set [param(200)]", "/attribute @p parcool:stamina_recovery base set [param(1.15)]", "/attribute @p ars_nouveau:ars_nouveau.perk.feather base set [param(0.005)]"]
	on_level_event = [" "]
	tip_to_display = "§7Afecta tu velocidad de movimiento"
	init_val_attribute_fifth = 20.0
	max_level = +inf
	base_value_per_point = 2.0
	lock = false

["Attribute 6"]
	display_name = "Precisión : "
	cmd_to_exc = ["/attribute @p attributeslib:crit_damage base set [param(0.1)]", "/attribute @p attributeslib:arrow_damage base set [param(0.1)]"]
	on_level_event = [" "]
	tip_to_display = "§7Aumenta el daño de arcos y ballestas"
	init_val_attribute_sixth = 15.0
	max_level = +inf
	base_value_per_point = 1.0
	lock = false

["Attribute 7"]
	display_name = "Don del Destino : "
	cmd_to_exc = ["/attribute @p generic.luck base set [param(4)]", "/attribute @p attributeslib:crit_chance base set [param(0.02)]"]
	on_level_event = [" "]
	tip_to_display = "§7El destino parece sonreírte."
	init_val_attribute_seventh = 1.0
	max_level = 50.0
	base_value_per_point = 1.0
	lock = false

["Attribute 8"]
	display_name = "Inteligencia : "
	cmd_to_exc = ["/attribute @p ars_nouveau:ars_nouveau.perk.spell_damage base set", "/attribute @p irons_spellbooks:spell_power base set", "/attribute @p ars_nouveau.perk.warding base set [param(0.5)]"]
	on_level_event = [" "]
	tip_to_display = "§7Aumenta el daño de tus magias y hechizos"
	init_val_attribute_eight = 1.0
	max_level = +inf
	base_value_per_point = 1.0
	lock = false

["Attribute 9"]
	"display_name " = "Bendición : "
	cmd_to_exc = [" /attribute @p irons_spellbooks:max_mana base set [param(10.0)]", "/attribute @p irons_spellbooks:mana_regen base set [param(0.005)]", "/attribute @p ars_nouveau.perk.max_mana base set [param(0.005)]", "/attribute @p ars_nouveau.perk.mana_regen base set [param(0.1)]", "/attribute @p irons_spellbooks:holy_spell_power base set [param(0.1)]"]
	on_level_event = [" "]
	"tip_to_display " = "Otorga una mayor reserva de Maná, aumenta tu regeneración de Maná y amplifica el poder de tus hechizos de curación y soporte."
	init_val_attribute_nine = 10.0
	max_level = +inf
	base_value_per_point = 1.0
	lock = false

["Attribute 10"]
	"display_name " = "Función inmortal : "
	cmd_to_exc = [" /attribute @p irons_spellbooks:cast_time_reduction base set [param(0.2)]", "/attribute @p irons_spellbooks:cooldown_reduction base set [param(0.2)]", "/attribute @p ars_nouveau.perk.wixie base set [param(0.5)]"]
	on_level_event = [" "]
	"tip_to_display " = "Disminuye el tiempo de casteo y optimiza la recuperación de tus habilidades."
	init_val_attribute_ten = 0.0
	max_level = +inf
	base_value_per_point = 1.0
	lock = false

