
[Blacklist]
	#write the registry name of the entities
	banned = [" "]
	death_messages = false
	locked_mobs = ["100/minecraft:ender_dragon", "150/minecraft:wither"]
	can_be_ascendant = ["minecraft:zombie", "minecraft:skeleton"]

